version: '3'

services:
  quarterflix_server:
    container_name: node_server
    build: .
    volumes:
      - "./src:/usr/src/app/quaterflix-backend/src"
    ports:
      - "80:80"
      - "9229:9229"
    links:
      - mongo_server
      - redis_server
  
  mongo_server:
    container_name: mongo_server
    image: mongo:4.0.11
    volumes:
      - "~/mongo_data:/data/db"
    ports:
      - "27017:27017"
    expose:
      - "27017"
  
  redis_server:
    container_name: redis_server
    image: redis:5
    expose:
     - "6379"